# HTTP Server
server:
  port: 12031  # HTTP (Tomcat) port

spring:
  application:
    name: ts-order-service
  data:
    mongodb:
      host: ts-order-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
      port: 27017

swagger:
  controllerPackage: order.controller