server:
  port: 15678  # HTTP (Tomcat) port

spring:

  application:
    name: ts-verification-code-service

  data:
    mongodb:
      host: ts-verification-code-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

