spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local
  application:
    name: ts-route-service
  datasource:
    url: jdbc:mysql://ts-route-mysql:3306/ts-route-mysql?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

# HTTP Server
server:
  port: 11178  # HTTP (Tomcat) port

swagger:
  controllerPackage: route.controller