spring:

  application:
    name: ts-sso-service

  data:
    mongodb:
      host: ts-account-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

  

# HTTP Server
server:
  port: 12349  # HTTP (Tomcat) port