spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local
  application:
    name: ts-consign-service
  datasource:
    url: jdbc:mysql://${CONSIGN_MYSQL_HOST:ts-consign-mysql}:${CONSIGN_MYSQL_PORT:3306}/${CONSIGN_MYSQL_DATABASE:ts-consign-mysql}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: ${CONSIGN_MYSQL_USER:root}
    password: ${CONSIGN_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


# HTTP Server
server:
  port: 16111

swagger:
  controllerPackage: consign.controller

consign-price-service:
  url: http://${CONSIGN_PRICE_SERVICE_HOST:ts-consign-price-service}:${CONSIGN_PRICE_SERVICE_PORT:16110}